export const WOW_CLASSES: Record<number, { name: string; color: string }> = {
  1: { name: 'Warrior', color: '#C79C6E' },
  2: { name: 'Paladin', color: '#F58CBA' },
  3: { name: 'Hunter', color: '#ABD473' },
  4: { name: 'Rogue', color: '#FFF569' },
  5: { name: 'Priest', color: '#FFFFFF' },
  6: { name: 'Death Knight', color: '#C41F3B' },
  7: { name: 'Shaman', color: '#0070DE' },
  8: { name: 'Mage', color: '#69CCF0' },
  9: { name: 'Warlock', color: '#9482C9' },
  11: { name: 'Druid', color: '#FF7D0A' },
};

export const WOW_RACES: Record<number, { name: string; faction: 'Alliance' | 'Horde' }> = {
  1: { name: 'Human', faction: 'Alliance' },
  2: { name: 'Orc', faction: 'Horde' },
  3: { name: 'Dwarf', faction: 'Alliance' },
  4: { name: 'Night Elf', faction: 'Alliance' },
  5: { name: 'Undead', faction: 'Horde' },
  6: { name: 'Tauren', faction: 'Horde' },
  7: { name: 'Gnome', faction: 'Alliance' },
  8: { name: 'Troll', faction: 'Horde' },
  10: { name: 'Blood Elf', faction: 'Horde' },
  11: { name: 'Draenei', faction: 'Alliance' },
};

export enum GmLevel {
  PLAYER = 0,
  MODERATOR = 1,
  GAMEMASTER = 2,
  ADMINISTRATOR = 3,
  CONSOLE = 4,
}

export const GM_LEVEL_NAMES: Record<number, string> = {
  [GmLevel.PLAYER]: 'Player',
  [GmLevel.MODERATOR]: 'Moderator',
  [GmLevel.GAMEMASTER]: 'Game Master',
  [GmLevel.ADMINISTRATOR]: 'Administrator',
  [GmLevel.CONSOLE]: 'Console',
};

export const FACTION_COLORS = {
  Alliance: '#0078FF',
  Horde: '#B30000',
} as const;

export const MAX_ACCOUNT_STR = 17;
export const MAX_PASS_STR = 16;
export const MAX_EMAIL_STR = 255;

export const WOW_ZONES: Record<number, string> = {
  // Eastern Kingdoms
  1: 'Dun Morogh',
  12: 'Elwynn Forest',
  14: 'Durotar',
  15: 'Dustwallow Marsh',
  17: 'The Barrens',
  28: 'Western Plaguelands',
  33: 'Stranglethorn Vale',
  38: 'Loch Modan',
  40: 'Westfall',
  44: 'Redridge Mountains',
  45: 'Arathi Highlands',
  46: 'Burning Steppes',
  47: 'The Hinterlands',
  51: 'Searing Gorge',
  65: 'Dragonblight',
  66: "Zul'Drak",
  67: 'The Storm Peaks',
  85: 'Tirisfal Glades',
  130: 'Silverpine Forest',
  139: 'Eastern Plaguelands',
  141: 'Teldrassil',
  148: 'Darkshore',
  206: 'Utgarde Keep',
  209: 'Shadowfang Keep',
  210: 'Icecrown',
  215: 'Mulgore',
  267: 'Hillsbrad Foothills',
  331: 'Ashenvale',
  357: 'Feralas',
  361: 'Felwood',
  394: 'Grizzly Hills',
  400: 'Thousand Needles',
  405: 'Desolace',
  406: 'Stonetalon Mountains',
  440: 'Tanaris',
  490: "Un'Goro Crater",
  491: 'Razorfen Kraul',
  493: 'Moonglade',
  495: 'Howling Fjord',
  618: 'Winterspring',
  717: 'Stormwind Stockade',
  718: 'Wailing Caverns',
  719: 'Blackfathom Deeps',
  721: 'Gnomeregan',
  722: 'Razorfen Downs',
  796: 'Scarlet Monastery',
  1176: "Zul'Farrak",
  1196: 'Utgarde Pinnacle',
  1337: 'Uldaman',
  1377: 'Silithus',
  1477: 'Sunken Temple',
  1497: 'Undercity',
  1519: 'Stormwind City',
  1537: 'Ironforge',
  1581: 'The Deadmines',
  1583: 'Blackrock Spire',
  1584: 'Blackrock Depths',
  1637: 'Orgrimmar',
  1638: 'Thunder Bluff',
  1657: 'Darnassus',
  1977: "Zul'Gurub",
  2017: 'Stratholme',
  2057: 'Scholomance',
  2100: 'Maraudon',
  2159: "Onyxia's Lair",
  2366: 'The Black Morass',
  2367: 'Old Hillsbrad Foothills',
  2557: 'Dire Maul',
  2597: 'Alterac Valley',
  2677: 'Blackwing Lair',
  2717: 'Molten Core',
  2817: 'Crystalsong Forest',
  3277: 'Warsong Gulch',
  3358: 'Arathi Basin',
  3428: "Temple of Ahn'Qiraj",
  3429: "Ruins of Ahn'Qiraj",
  3430: 'Eversong Woods',
  3433: 'Ghostlands',
  3456: 'Naxxramas',
  3457: 'Karazhan',
  3483: 'Hellfire Peninsula',
  3487: 'Silvermoon City',
  3518: 'Nagrand',
  3519: 'Terokkar Forest',
  3520: 'Shadowmoon Valley',
  3521: 'Zangarmarsh',
  3522: "Blade's Edge Mountains",
  3523: 'Netherstorm',
  3524: 'Azuremyst Isle',
  3525: 'Bloodmyst Isle',
  3537: 'Borean Tundra',
  3557: 'The Exodar',
  3562: 'Hellfire Ramparts',
  3606: 'Hyjal Summit',
  3607: 'Serpentshrine Cavern',
  3698: 'Nagrand Arena',
  3702: "Blade's Edge Arena",
  3703: 'Shattrath City',
  3711: 'Sholazar Basin',
  3713: 'The Blood Furnace',
  3714: 'The Shattered Halls',
  3715: 'The Steamvault',
  3716: 'The Underbog',
  3717: 'The Slave Pens',
  3789: 'Shadow Labyrinth',
  3790: 'Auchenai Crypts',
  3791: 'Sethekk Halls',
  3792: 'Mana-Tombs',
  3820: 'Eye of the Storm',
  3836: "Magtheridon's Lair",
  3845: 'Tempest Keep',
  3847: 'The Botanica',
  3848: 'The Arcatraz',
  3849: 'The Mechanar',
  3923: "Gruul's Lair",
  3959: 'Black Temple',
  3968: 'Ruins of Lordaeron',
  4075: 'Sunwell Plateau',
  4080: "Isle of Quel'Danas",
  4100: 'The Culling of Stratholme',
  4131: "Magisters' Terrace",
  4196: "Drak'Tharon Keep",
  4197: 'Wintergrasp',
  4228: 'The Oculus',
  4264: 'Halls of Stone',
  4265: 'The Nexus',
  4272: 'Halls of Lightning',
  4273: 'Ulduar',
  4277: 'Azjol-Nerub',
  4378: 'Dalaran Sewers',
  4384: 'Strand of the Ancients',
  4395: 'Dalaran',
  4406: 'Ring of Valor',
  4415: 'The Violet Hold',
  4416: 'Gundrak',
  4493: 'The Obsidian Sanctum',
  4494: "Ahn'kahet: The Old Kingdom",
  4500: 'The Eye of Eternity',
  4603: 'Vault of Archavon',
  4710: 'Isle of Conquest',
  4722: 'Trial of the Crusader',
  4723: 'Trial of the Champion',
  4742: "Hrothgar's Landing",
  4809: 'The Forge of Souls',
  4812: 'Icecrown Citadel',
  4813: 'Pit of Saron',
  4820: 'Halls of Reflection',
  4987: 'The Ruby Sanctum',
};

export function getZoneName(zoneId: number): string {
  return WOW_ZONES[zoneId] ?? `Zone ${zoneId}`;
}

// ── Item constants ──

export const ITEM_QUALITY_COLORS: Record<number, string> = {
  0: '#9d9d9d', // Poor (grey)
  1: '#ffffff', // Common (white)
  2: '#1eff00', // Uncommon (green)
  3: '#0070dd', // Rare (blue)
  4: '#a335ee', // Epic (purple)
  5: '#ff8000', // Legendary (orange)
  6: '#e6cc80', // Artifact (light gold)
  7: '#00ccff', // Heirloom (light blue)
};

export function getItemQualityColor(quality: number): string {
  return ITEM_QUALITY_COLORS[quality] ?? '#ffffff';
}

export const ITEM_BONDING: Record<number, string> = {
  1: 'Binds when picked up',
  2: 'Binds when equipped',
  3: 'Binds when used',
  4: 'Quest Item',
};

export const ITEM_INVENTORY_TYPE: Record<number, string> = {
  0: '',
  1: 'Head',
  2: 'Neck',
  3: 'Shoulder',
  4: 'Shirt',
  5: 'Chest',
  6: 'Waist',
  7: 'Legs',
  8: 'Feet',
  9: 'Wrists',
  10: 'Hands',
  11: 'Finger',
  12: 'Trinket',
  13: 'One-Hand',
  14: 'Shield',
  15: 'Ranged',
  16: 'Back',
  17: 'Two-Hand',
  18: 'Bag',
  19: 'Tabard',
  20: 'Robe',
  21: 'Main Hand',
  22: 'Off Hand',
  23: 'Holdable',
  24: 'Ammo',
  25: 'Thrown',
  26: 'Ranged Right',
  28: 'Relic',
};

export const ITEM_STAT_NAMES: Record<number, string> = {
  0: 'Mana',
  1: 'Health',
  3: 'Agility',
  4: 'Strength',
  5: 'Intellect',
  6: 'Spirit',
  7: 'Stamina',
  12: 'Defense Rating',
  13: 'Dodge Rating',
  14: 'Parry Rating',
  15: 'Block Rating',
  16: 'Melee Hit Rating',
  17: 'Ranged Hit Rating',
  18: 'Spell Hit Rating',
  19: 'Melee Crit Rating',
  20: 'Ranged Crit Rating',
  21: 'Spell Crit Rating',
  22: 'Melee Haste Rating',
  23: 'Ranged Haste Rating',
  24: 'Spell Haste Rating',
  25: 'Hit Rating',
  26: 'Crit Rating',
  27: 'Haste Rating',
  28: 'Hit Rating',
  29: 'Crit Rating',
  30: 'Haste Rating',
  31: 'Hit Rating',
  32: 'Crit Rating',
  35: 'Resilience Rating',
  36: 'Haste Rating',
  37: 'Expertise Rating',
  38: 'Attack Power',
  39: 'Ranged Attack Power',
  40: 'Feral Attack Power',
  41: 'Spell Healing',
  42: 'Spell Damage',
  43: 'Mana Regeneration',
  44: 'Armor Penetration Rating',
  45: 'Spell Power',
  46: 'Health Regeneration',
  47: 'Spell Penetration',
  48: 'Block Value',
};

/** Primary attributes displayed as white "+X Stat" lines in tooltips */
export const PRIMARY_STAT_TYPES = new Set([0, 1, 3, 4, 5, 6, 7]);

/** Equip effect text for green "Equip:" tooltip lines (WoW-style phrasing) */
export const EQUIP_STAT_TEXT: Record<number, string> = {
  12: 'Increases defense rating by',
  13: 'Increases your dodge rating by',
  14: 'Increases your parry rating by',
  15: 'Increases your shield block rating by',
  16: 'Improves melee hit rating by',
  17: 'Improves ranged hit rating by',
  18: 'Improves spell hit rating by',
  19: 'Improves melee critical strike rating by',
  20: 'Improves ranged critical strike rating by',
  21: 'Improves spell critical strike rating by',
  22: 'Improves melee haste rating by',
  23: 'Improves ranged haste rating by',
  24: 'Improves spell haste rating by',
  25: 'Improves hit rating by',
  26: 'Improves critical strike rating by',
  27: 'Improves haste rating by',
  28: 'Improves hit rating by',
  29: 'Improves critical strike rating by',
  30: 'Improves haste rating by',
  31: 'Improves hit rating by',
  32: 'Improves critical strike rating by',
  35: 'Improves your resilience rating by',
  36: 'Improves haste rating by',
  37: 'Increases your expertise rating by',
  38: 'Increases attack power by',
  39: 'Increases ranged attack power by',
  40: 'Increases attack power in feral forms by',
  41: 'Increases healing done by up to',
  42: 'Increases damage done by up to',
  43: 'Restores',
  44: 'Increases your armor penetration rating by',
  45: 'Increases spell power by',
  46: 'Restores',
  47: 'Increases spell penetration by',
  48: 'Increases the block value of your shield by',
};

export const ITEM_CLASS_NAMES: Record<number, string> = {
  0: 'Consumable',
  1: 'Container',
  2: 'Weapon',
  3: 'Gem',
  4: 'Armor',
  5: 'Reagent',
  6: 'Projectile',
  7: 'Trade Goods',
  9: 'Recipe',
  11: 'Quiver',
  12: 'Quest',
  13: 'Key',
  15: 'Miscellaneous',
  16: 'Glyph',
};

export const ARMOR_SUBCLASS_NAMES: Record<number, string> = {
  0: 'Miscellaneous',
  1: 'Cloth',
  2: 'Leather',
  3: 'Mail',
  4: 'Plate',
  6: 'Shield',
  7: 'Libram',
  8: 'Idol',
  9: 'Totem',
  10: 'Sigil',
};

export const WEAPON_SUBCLASS_NAMES: Record<number, string> = {
  0: 'Axe',
  1: 'Axe',
  2: 'Bow',
  3: 'Gun',
  4: 'Mace',
  5: 'Mace',
  6: 'Polearm',
  7: 'Sword',
  8: 'Sword',
  9: 'Obsolete',
  10: 'Staff',
  13: 'Fist Weapon',
  14: 'Miscellaneous',
  15: 'Dagger',
  16: 'Thrown',
  18: 'Crossbow',
  19: 'Wand',
  20: 'Fishing Pole',
};

export const DAMAGE_TYPE_NAMES: Record<number, string> = {
  0: '',
  1: 'Holy',
  2: 'Fire',
  3: 'Nature',
  4: 'Frost',
  5: 'Shadow',
  6: 'Arcane',
};
